{% set name = "pydantic-settings" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 06f0062169818d0f5524420a360d632d5857b83cffd4d42fe29597807a1614ee

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - pydantic >=2.7.0
    - python-dotenv >=0.21.0
    - typing-inspection >=0.4.0
  run_constrained:
    # yaml
    - pyyaml >=6.0.1
    # toml
    - tomli >=2.0.1
    # azure-key-vault
    - azure-keyvault-secrets >=4.8.0
    - azure-identity >=1.16.0
    # aws-secrets-manager
    - boto3>=1.35.0
    # gcp-secret-manager
    - google-cloud-secret-manager>=2.23.1

test:
  source_files:
    - tests
  imports:
    - pydantic_settings
  commands:
    - pip check
    # Missed module pytest_examples for test_docs.py 
    - pytest -v tests --ignore=tests/test_docs.py
  requires:
    - pip
    - pytest
    - pytest-mock

about:
  home: https://github.com/pydantic/pydantic-settings
  summary: Settings management using Pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Pydantic Settings provides optional Pydantic features for loading a settings or config class from environment
    variables or secrets files.
  dev_url: https://github.com/pydantic/pydantic-settings
  doc_url: https://docs.pydantic.dev/latest/usage/pydantic_settings

extra:
  recipe-maintainers:
    - jan-janssen
    - fhoehle
