{% set name = "pydantic-settings" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_settings-{{ version }}.tar.gz
  sha256: 962dc3672495aad6ae96a4390fac7e593591e144625e5112d359f8f67fb75945

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=2
    - python-dotenv >=0.21.0

test:
  imports:
    - pydantic_settings
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Settings management using Pydantic
  home: https://github.com/pydantic/pydantic-settings
  dev_url: https://github.com/pydantic/pydantic-settings
  doc_url: https://docs.pydantic.dev/latest/usage/pydantic_settings/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
